# Generated by Django 5.1.1 on 2024-10-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_deliveryaddress_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
