# Generated by Django 5.1.1 on 2024-10-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deliveryaddress_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='postal_code',
        ),
    ]
