# Generated by Django 5.1.1 on 2024-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_deliveryaddress_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='totaldeliveryPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
