# Generated by Django 5.1.1 on 2024-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deliveryaddress_totaldeliveryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
